INSERT INTO ulkeler ('name', 'ad') VALUES("Andorra", "Andorra"),
("Europe", "Avrupa"),
("United Arab Emirates", "Birleşik Arap Emirlikleri"),
("Asia", "Asya"),
("Afghanistan", "Afganistan"),
("Asia", "Asya"),
("Antigua and Barbuda", "Antigua ve Barbuda"),
("North America", "Kuzey Amerika"),
("Anguilla", "Anguilla"),
("North America", "Kuzey Amerika"),
("Albania", "Arnavutluk"),
("Europe", "Avrupa"),
("Armenia", "Ermenistan"),
("Asia", "Asya"),
("Angola", "Angola"),
("Africa", "Afrika"),
("Argentina", "Arjantin"),
("South America", "Güney Amerika"),
("American Samoa", "Amerikan Samoası"),
("Oceania", "Okyanusya"),
("Austria", "Avusturya"),
("Europe", "Avrupa"),
("Australia", "Avustralya"),
("Oceania", "Okyanusya"),
("Aruba", "Aruba"),
("North America", "Kuzey Amerika"),
("Åland", "Åland"),
("Europe", "Avrupa"),
("Azerbaijan", "Azerbaycan"),
("Asia", "Asya"),
("Bosnia and Herzegovina", "Bosna-Hersek"),
("Europe", "Avrupa"),
("Barbados", "Barbados"),
("North America", "Kuzey Amerika"),
("Bangladesh", "Bangladeş"),
("Asia", "Asya"),
("Belgium", "Belçika"),
("Europe", "Avrupa"),
("Burkina Faso", "Burkina Faso"),
("Africa", "Afrika"),
("Bulgaria", "Bulgaristan"),
("Europe", "Avrupa"),
("Bahrain", "Bahreyn"),
("Asia", "Asya"),
("Burundi", "Burundi"),
("Africa", "Afrika"),
("Benin", "Benin"),
("Africa", "Afrika"),
("Saint Barthélemy", "Saint Barthélemy"),
("North America", "Kuzey Amerika"),
("Bermuda", "Bermuda"),
("North America", "Kuzey Amerika"),
("Brunei", "Brunei"),
("Asia", "Asya"),
("Bolivia", "Bolivya"),
("South America", "Güney Amerika"),
("Bonaire", "Bonaire"),
("North America", "Kuzey Amerika"),
("Brazil", "Brezilya"),
("South America", "Güney Amerika"),
("Bahamas", "Bahamalar"),
("North America", "Kuzey Amerika"),
("Bhutan", "Bhutan"),
("Asia", "Asya"),
("Bouvet Island", "Bouvet Adası"),
("Antarctica", "Antarktika"),
("Botswana", "Botsvana"),
("Africa", "Afrika"),
("Belarus", "Beyaz Rusya"),
("Europe", "Avrupa"),
("Belize", "Belize"),
("North America", "Kuzey Amerika"),
("Canada", "Kanada"),
("North America", "Kuzey Amerika"),
("Cocos Islands", "Cocos Adaları"),
("Asia", "Asya"),
("Democratic Republic of the Congo", "Demokratik Kongo Cumhuriyeti"),
("Africa", "Afrika"),
("Central African Republic", "Orta Afrika Cumhuriyeti"),
("Africa", "Afrika"),
("Republic of the Congo", "Kongo Cumhuriyeti"),
("Africa", "Afrika"),
("Switzerland", "İsviçre"),
("Europe", "Avrupa"),
("Ivory Coast", "Fildişi Sahili"),
("Africa", "Afrika"),
("Cook Islands", "Cook Adaları"),
("Oceania", "Okyanusya"),
("Chile", "Şili"),
("South America", "Güney Amerika"),
("Cameroon", "Kamerun"),
("Africa", "Afrika"),
("China", "Çin Halk Cumhuriyeti"),
("Asia", "Asya"),
("Colombia", "Kolombiya"),
("South America", "Güney Amerika"),
("Costa Rica", "Kosta Rika"),
("North America", "Kuzey Amerika"),
("Cuba", "Küba"),
("North America", "Kuzey Amerika"),
("Cape Verde", "Yeşil Burun Adaları"),
("Africa", "Afrika"),
("Curacao", "Curaçao"),
("North America", "Kuzey Amerika"),
("Christmas Island", "Christmas Adası"),
("Asia", "Asya"),
("Czech Republic", "Çek Cumhuriyeti"),
("Europe", "Avrupa"),
("Germany", "Almanya"),
("Europe", "Avrupa"),
("Djibouti", "Cibuti"),
("Africa", "Afrika"),
("Denmark", "Danimarka"),
("Europe", "Avrupa"),
("Dominica", "Dominika"),
("North America", "Kuzey Amerika"),
("Dominican Republic", "Dominik Cumhuriyeti"),
("North America", "Kuzey Amerika"),
("Algeria", "Cezayir"),
("Africa", "Afrika"),
("Ecuador", "Ekvador"),
("South America", "Güney Amerika"),
("Estonia", "Estonya"),
("Europe", "Avrupa"),
("Egypt", "Mısır"),
("Africa", "Afrika"),
("Western Sahara", "Batı Sahra"),
("Africa", "Afrika"),
("Eritrea", "Eritre"),
("Africa", "Afrika"),
("Spain", "İspanya"),
("Europe", "Avrupa"),
("Ethiopia", "Etiyopya"),
("Africa", "Afrika"),
("Finland", "Finlandiya"),
("Europe", "Avrupa"),
("Fiji", "Fiji"),
("Oceania", "Okyanusya"),
("Falkland Islands", "Falkland Adaları"),
("South America", "Güney Amerika"),
("Micronesia", "Mikronezya"),
("Oceania", "Okyanusya"),
("Faroe Islands", "Faroe Adaları"),
("Europe", "Avrupa"),
("France", "Fransa"),
("Europe", "Avrupa"),
("Gabon", "Gabon"),
("Africa", "Afrika"),
("United Kingdom", "Birleşik Krallık"),
("Europe", "Avrupa"),
("Grenada", "Grenada"),
("North America", "Kuzey Amerika"),
("Georgia", "Gürcistan"),
("Asia", "Asya"),
("French Guiana", "Fransız Guyanası"),
("South America", "Güney Amerika"),
("Guernsey", "Guernsey"),
("Europe", "Avrupa"),
("Ghana", "Gana"),
("Africa", "Afrika"),
("Gibraltar", "Cebelitarık"),
("Europe", "Avrupa"),
("Greenland", "Grönland"),
("North America", "Kuzey Amerika"),
("Gambia", "Gambiya"),
("Africa", "Afrika"),
("Guinea", "Gine"),
("Africa", "Afrika"),
("Guadeloupe", "Guadeloupe"),
("North America", "Kuzey Amerika"),
("Equatorial Guinea", "Ekvator Ginesi"),
("Africa", "Afrika"),
("Greece", "Yunanistan"),
("Europe", "Avrupa"),
("South Georgia and the South Sandwich Islands", "Güney Georgia ve Güney Sandwich Adaları"),
("Antarctica", "Antarktika"),
("Guatemala", "Guatemala"),
("North America", "Kuzey Amerika"),
("Guam", "Guam"),
("Oceania", "Okyanusya"),
("Guinea-Bissau", "Gine-Bissau"),
("Africa", "Afrika"),
("Guyana", "Guyana"),
("South America", "Güney Amerika"),
("Hong Kong", "Hong Kong"),
("Asia", "Asya"),
("Heard Island and McDonald Islands", "Heard Adası ve McDonald Adaları"),
("Antarctica", "Antarktika"),
("Honduras", "Honduras"),
("North America", "Kuzey Amerika"),
("Croatia", "Hırvatistan"),
("Europe", "Avrupa"),
("Haiti", "Haiti"),
("North America", "Kuzey Amerika"),
("Hungary", "Macaristan"),
("Europe", "Avrupa"),
("Indonesia", "Endonezya"),
("Asia", "Asya"),
("Ireland", "İrlanda"),
("Europe", "Avrupa"),
("Israel", "İsrail"),
("Asia", "Asya"),
("Isle of Man", "Man Adası"),
("Europe", "Avrupa"),
("India", "Hindistan"),
("Asia", "Asya"),
("British Indian Ocean Territory", "Britanya Hint Okyanusu Toprakları"),
("Asia", "Asya"),
("Iraq", "Irak"),
("Asia", "Asya"),
("Iran", "İran"),
("Asia", "Asya"),
("Iceland", "İzlanda"),
("Europe", "Avrupa"),
("Italy", "İtalya"),
("Europe", "Avrupa"),
("Jersey", "Jersey"),
("Europe", "Avrupa"),
("Jamaica", "Jamaika"),
("North America", "Kuzey Amerika"),
("Jordan", "Ürdün"),
("Asia", "Asya"),
("Japan", "Japonya"),
("Asia", "Asya"),
("Kenya", "Kenya"),
("Africa", "Afrika"),
("Kyrgyzstan", "Kırgızistan"),
("Asia", "Asya"),
("Cambodia", "Kamboçya"),
("Asia", "Asya"),
("Kiribati", "Kiribati"),
("Oceania", "OkyanusyaKKTC"),
("Northern Cyprus", "Kuzey Kıbrıs Türk Cumhuriyeti"),
("Europe", "Avrupa"),
("Comoros", "Komorlar"),
("Africa", "Afrika"),
("Saint Kitts and Nevis", "Saint Kitts ve Nevis"),
("North America", "Kuzey Amerika"),
("North Korea", "Kuzey Kore"),
("Asia", "Asya"),
("South Korea", "Güney Kore"),
("Asia", "Asya"),
("Kuwait", "Kuveyt"),
("Asia", "Asya"),
("Cayman Islands", "Cayman Adaları"),
("North America", "Kuzey Amerika"),
("Kazakhstan", "Kazakistan"),
("Asia", "Asya"),
("Laos", "Laos"),
("Asia", "Asya"),
("Lebanon", "Lübnan"),
("Asia", "Asya"),
("Saint Lucia", "Saint Lucia"),
("North America", "Kuzey Amerika"),
("Liechtenstein", "Lihtenştayn"),
("Europe", "Avrupa"),
("Sri Lanka", "Sri Lanka"),
("Asia", "Asya"),
("Liberia", "Liberya"),
("Africa", "Afrika"),
("Lesotho", "Lesotho"),
("Africa", "Afrika"),
("Lithuania", "Litvanya"),
("Europe", "Avrupa"),
("Luxembourg", "Lüksemburg"),
("Europe", "Avrupa"),
("Latvia", "Letonya"),
("Europe", "Avrupa"),
("Libya", "Libya"),
("Africa", "Afrika"),
("Morocco", "Fas"),
("Africa", "Afrika"),
("Monaco", "Monako"),
("Europe", "Avrupa"),
("Moldova", "Moldova"),
("Europe", "Avrupa"),
("Montenegro", "Karadağ"),
("Europe", "Avrupa"),
("Saint Martin", "Saint Martin"),
("North America", "Kuzey Amerika"),
("Madagascar", "Madagaskar"),
("Africa", "Afrika"),
("Marshall Islands", "Marshall Adaları"),
("Oceania", "Okyanusya"),
("Macedonia", "Makedonya"),
("Europe", "Avrupa"),
("Mali", "Mali"),
("Africa", "Afrika"),
("Myanmar", "Myanmar"),
("Asia", "Asya"),
("Mongolia", "Moğolistan"),
("Asia", "Asya"),
("Macau", "Makao"),
("Asia", "Asya"),
("Northern Mariana Islands", "Kuzey Mariana Adaları"),
("Oceania", "Okyanusya"),
("Martinique", "Martinique"),
("North America", "Kuzey Amerika"),
("Mauritania", "Moritanya"),
("Africa", "Afrika"),
("Montserrat", "Montserrat"),
("North America", "Kuzey Amerika"),
("Malta", "Malta"),
("Europe", "Avrupa"),
("Mauritius", "Mauritius"),
("Africa", "Afrika"),
("Maldives", "Maldivler"),
("Asia", "Asya"),
("Malawi", "Malavi"),
("Africa", "Afrika"),
("Mexico", "Meksika"),
("North America", "Kuzey Amerika"),
("Malaysia", "Malezya"),
("Asia", "Asya"),
("Mozambique", "Mozambik"),
("Africa", "Afrika"),
("Namibia", "Namibya"),
("Africa", "Afrika"),
("New Caledonia", "Yeni Kaledonya"),
("Oceania", "Okyanusya"),
("Niger", "Nijer"),
("Africa", "Afrika"),
("Norfolk Island", "Norfolk Adası"),
("Oceania", "Okyanusya"),
("Nigeria", "Nijerya"),
("Africa", "Afrika"),
("Nicaragua", "Nikaragua"),
("North America", "Kuzey Amerika"),
("Netherlands", "Hollanda"),
("Europe", "Avrupa"),
("Norway", "Norveç"),
("Europe", "Avrupa"),
("Nepal", "Nepal"),
("Asia", "Asya"),
("Nauru", "Nauru"),
("Oceania", "Okyanusya"),
("Niue", "Niue"),
("Oceania", "Okyanusya"),
("New Zealand", "Yeni Zelanda"),
("Oceania", "Okyanusya"),
("Oman", "Umman"),
("Asia", "Asya"),
("Panama", "Panama"),
("North America", "Kuzey Amerika"),
("Peru", "Peru"),
("South America", "Güney Amerika"),
("French Polynesia", "Fransız Polinezyası"),
("Oceania", "Okyanusya"),
("Papua New Guinea", "Papua Yeni Gine"),
("Oceania", "Okyanusya"),
("Philippines", "Filipinler"),
("Asia", "Asya"),
("Pakistan", "Pakistan"),
("Asia", "Asya"),
("Poland", "Polonya"),
("Europe", "Avrupa"),
("Saint Pierre and Miquelon", "Saint Pierre ve Miquelon"),
("North America", "Kuzey Amerika"),
("Pitcairn Islands", "Pitcairn Adaları"),
("Oceania", "Okyanusya"),
("Puerto Rico", "Porto Riko"),
("North America", "Kuzey Amerika"),
("Palestine", "Filistin"),
("Asia", "Asya"),
("Portugal", "Portekiz"),
("Europe", "Avrupa"),
("Palau", "Palau"),
("Oceania", "Okyanusya"),
("Paraguay", "Paraguay"),
("South America", "Güney Amerika"),
("Qatar", "Katar"),
("Asia", "Asya"),
("Réunion", "Réunion"),
("Africa", "Afrika"),
("Romania", "Romanya"),
("Europe", "Avrupa"),
("Serbia", "Sırbistan"),
("Europe", "Avrupa"),
("Russia", "Rusya"),
("Europe", "Avrupa"),
("Rwanda", "Ruanda"),
("Africa", "Afrika"),
("Saudi Arabia", "Suudi Arabistan"),
("Asia", "Asya"),
("Solomon Islands", "Solomon Adaları"),
("Oceania", "Okyanusya"),
("Seychelles", "Seyşeller"),
("Africa", "Afrika"),
("Sudan", "Sudan"),
("Africa", "Afrika"),
("Sweden", "İsveç"),
("Europe", "Avrupa"),
("Singapore", "Singapur"),
("Asia", "Asya"),
("Saint Helena", "Saint Helena"),
("Africa", "Afrika"),
("Slovenia", "Slovenya"),
("Europe", "Avrupa"),
("Svalbard and Jan Mayen", "Svalbard and Jan Mayen"),
("Europe", "Avrupa"),
("Slovakia", "Slovakya"),
("Europe", "Avrupa"),
("Sierra Leone", "Sierra Leone"),
("Africa", "Afrika"),
("San Marino", "San Marino"),
("Europe", "Avrupa"),
("Senegal", "Senegal"),
("Africa", "Afrika"),
("Somalia", "Somali"),
("Africa", "Afrika"),
("Suriname", "Surinam"),
("South America", "Güney Amerika"),
("South Sudan", "Güney Sudan"),
("Africa", "Afrika"),
("São Tomé and Príncipe", "São Tomé ve Príncipe"),
("Africa", "Afrika"),
("El Salvador", "El Salvador"),
("North America", "Kuzey Amerika"),
("Sint Maarten", "Sint Maarten"),
("North America", "Kuzey Amerika"),
("Syria", "Suriye"),
("Asia", "Asya"),
("Swaziland", "Svaziland"),
("Africa", "Afrika"),
("Turks and Caicos Islands", "Turks ve Caicos Adaları"),
("North America", "Kuzey Amerika"),
("Chad", "Çad"),
("Africa", "Afrika"),
("French Southern Territories", "Fransız Güney ve Antarktika Toprakları"),
("Antarctica", "Antarktika"),
("Togo", "Togo"),
("Africa", "Afrika"),
("Thailand", "Tayland"),
("Asia", "Asya"),
("Tajikistan", "Tacikistan"),
("Asia", "Asya"),
("Tokelau", "Tokelau"),
("Oceania", "Okyanusya"),
("East Timor", "Doğu Timor"),
("Oceania", "Okyanusya"),
("Turkmenistan", "Türkmenistan"),
("Asia", "Asya"),
("Tunisia", "Tunus"),
("Africa", "Afrika"),
("Tonga", "Tonga"),
("Oceania", "Okyanusya"),
("Turkey", "Türkiye"),
("Asia", "Asya"),
("Trinid and Tobago", "Trinid ve Tobago"),
("North America", "Kuzey Amerika"),
("Tuvalu", "Tuvalu"),
("Oceania", "Okyanusya"),
("Taiwan", "Tayvan"),
("Asia", "Asya"),
("Tanzania", "Tanzanya"),
("Africa", "Afrika"),
("Ukraine", "Ukrayna"),
("Europe", "Avrupa"),
("Uganda", "Uganda"),
("Africa", "Afrika"),
("U.S. Minor Outlying Islands", "U.S. Minor Outlying Islands"),
("Oceania", "Okyanusya"),
("United States", "Amerika Birleşik Devletleri"),
("North America", "Kuzey Amerika"),
("Uruguay", "Uruguay"),
("South America", "Güney Amerika"),
("Uzbekistan", "Özbekistan"),
("Asia", "Asya"),
("Vatican City", "Vatikan"),
("Europe", "Avrupa"),
("Saint Vincent and the Grenadines", "Saint Vincent ve Grenadinler"),
("North America", "Kuzey Amerika"),
("Venezuela", "Venezuela"),
("South America", "Güney Amerika"),
("British Virgin Islands", "Britanya Virjin Adaları"),
("North America", "Kuzey Amerika"),
("U.S. Virgin Islands", "ABD Virjin Adaları"),
("North America", "Kuzey Amerika"),
("Vietnam", "Vietnam"),
("Asia", "Asya"),
("Vanuatu", "Vanuatu"),
("Oceania", "Okyanusya"),
("Wallis and Futuna", "Wallis ve Futuna Adaları"),
("Oceania", "Okyanusya"),
("Samoa", "Samoa"),
("Oceania", "Okyanusya"),
("Kosovo", "Kosova"),
("Europe", "Avrupa"),
("Yemen", "Yemen"),
("Asia", "Asya"),
("Mayotte", "Mayotte"),
("Africa", "Afrika"),
("South Africa", "Güney Afrika Cumhuriyeti"),
("Africa", "Afrika"),
("Zambia", "Zambiya"),
("Africa", "Afrika"),
("Zimbabwe", "Zimbabve"),
("Africa", "Afrika");
